### ISSUE TITLE
[CORE 0006] SMTP E Mail Client

### ISSUE THREAD

**Issue by leder11011** [ElmarDott/TP-CORE#11]
Hello Marco,
I cannot see the sample code for the email client working.

Do you have a clue?

Cheers
Gerrit

**Comment by leder11011** [comment]
Hello Marco,

I cannot even invoke the properties loading from the API:
private MailClient client = new JavaMailClient();

client.clearRecipents();
client.clearAttachments();
and
client.loadConfigurationFromProperties("org/europa/together/properties/mail-test.properties");
does not work!


Cheers
Gerrit

Gesendet von Mail für Windows 10

Von: Elmar Dott
Gesendet: Freitag, 15. November 2019 10:00
An: ElmarDott/TP-CORE
Cc: leder11011; Author
Betreff: Re: [ElmarDott/TP-CORE] [CORE 0006] SMTP E Mail Client (#11)

you need a well smtp configuration to your server. check the crypto settings.

regards
. m

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by ElmarDott** [comment]
du musst schon eine eigene property anlegen und mit einem richtigen email konto verbinden z. B. gmail :-) die inkludierten configurationen sind templates und für tests.
wie gesagt kannst gern mal anrufen dann erklär ich dir ein wenig wie das alles in einem eigenen projekt benutzt wird.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
