### ISSUE TITLE
maven-war-plugin defined

### ISSUE THREAD

**Issue by khmarbaise** [ElmarDott/TP-CORE#12]
Why is the maven-war-plugin defined but using the skip configuration? Does not make sense cause the packaging is `jar`?

**Comment by ElmarDott** [comment]
This was some legacy code - I removed now. 
Lessons learned: build logic needs also regular refactorings.

**Comment by ElmarDott** [comment]
This was some legacy code - I removed now. 
Lessons learned: build logic needs also regular refactorings.
