### ISSUE TITLE
cloning the master branch has unmet pom.xml dependancies

### ISSUE THREAD

**Issue by leder11011** [ElmarDott/TP-CORE#7]
Hello Elmar,

thanks for your library: I have one obstacle building it!
``
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.github.together.modules:core:2.0-SNAPSHOT (/home/leder/Git/TP-CORE/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.github.together.modules:core:2.0-SNAPSHOT: Failure to find io.github.together:build-workflow:pom:1.1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 15, column 13 -> [Help 2]
``
Can you help me out, plz!
Cheers
Gerrit

**Comment by ElmarDott** [comment]
I need to release version 2.0 and the parent pom. i did huge changes between the last publish release at mvn central.
version 2.0 is for java 9 and above.

i will provide during today a final version of tp core

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by ElmarDott** [comment]
TP-CORE 2.0 released to MVN central - including the corresponding POM form TP-CM/build-workflow
