### ISSUE TITLE
'mvn test' gives one Failure due to hard coded file path

### ISSUE THREAD

**Issue by leder11011** [ElmarDott/TP-CORE#9]
Hello Elmar,
thanks again for the release 2.0!
I have not all tests successful: 
- one failure due to a hard coded file path

This is the log:

-----------------------
```
[ERROR] Failures:
[ERROR]   FileUtilsTest.testListFileTree:149 expected: </media/veracrypt1/workspace/togetherPlatform/modules/core/target/test-classes/dir-test/level_1.0/file_a.txt> but was: </home/leder/Git/TP-CORE/target/test-classes/dir-test/level_1.0/file_a.txt>
[INFO]
[ERROR] Tests run: 258, Failures: 1, Errors: 0, Skipped: 8
[INFO]
[ERROR] There are test failures.
```
-----------------------

**Comment by ElmarDott** [comment]
Thx for the reporting the issue. I will try to fix it this week, because I'm traveling.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by ElmarDott** [comment]
Test case is fixed and path selection should now dynamic.
